name: visual_bookmarking_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.1.0
  firebase_core: ^3.15.0
  firebase_storage: ^12.3.5
  cloud_firestore: ^5.6.10
  image_picker: ^0.8.7+4 
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  # android_intent_plus: ^3.1.9
  url_launcher: ^6.2.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
